### ISSUE TITLE
Cannot log in via Google+

### ISSUE THREAD

**Issue by maurezen** [netbout/netbout#538]
While trying to log in via Google+ all I get is 400 error (redirect_uri_mismatch).

![netbout_redirect_error](https://cloud.githubusercontent.com/assets/569536/5619208/2cd0446e-9539-11e4-9ee9-32fa6f35829a.png)

**Comment by karato** [comment]
I'll find a developer for the task soon...

**Comment by karato** [comment]
@maurezen thanks for reporting! I topped your account for 15 mins, transaction 49904077

**Comment by yegor256** [comment]
@rultor release, tag is `2.11.3`

**Comment by yegor256** [comment]
@maurezen please check now and close the ticket if it works

**Comment by maurezen** [comment]
works for me now.
